### ISSUE TITLE
Result pagination

### ISSUE THREAD

**Issue by saintx** [CiscoSecurity/tr-05-api-module#37]
CTIA returns a limit of 100 results, but it also returns headers with the total number of results and information for paging.  We should expose that information through the API for users.

**Comment by gdavoian** [comment]
Hi @saintx, thank you for reporting the issue. After discussing this issue with @maugertg, we've decided to introduce an additional parameter allowing all the existing endpoints to return the raw response object instead of automatically decoding and returning it in JSON. This parameter is optional and called `response_type`, and supports the following values (at least so far): `raw` and `json`. The default value is `json`, because most of the time only the actual data is needed.

Here're some usage examples:
```python
data = tr.enrich.health(response_type='json')
data = tr.enrich.health()  # both calls are equivalent
```
or
```python
response = tr.enrich.health(response_type='raw')
print(response.headers)
data = response.json()  # decode explicitly
```

Please let us know whether the issue can be closed.
