### ISSUE TITLE
Sightings usage

### ISSUE THREAD

**Issue by Link009** [CiscoSecurity/tr-05-api-module#65]
Hi

How do I use Sightings function after it's instantiation ? I would like to see some code example because I can't make it work (various errors).

This is my code:

```
from __future__ import print_function

import time
import json
from threatresponse import ThreatResponse


def cisco_client():
    client = ThreatResponse(
        client_id='MY_CLIENT_ID',
        client_password='MY_PASSWORD',
        region='eu',
        timeout=900)

    time.sleep(1)
    return client


def cisco_sighting(value, client):
    sightings = client.private_intel.sighting.post({'query': '{}'.format(value)})  # ({'content': '{}'.format(value)})

    time.sleep(1)
    return sightings


value = "https://pressabpacam1988.blogspot.ru/"

client = cisco_client()
inspect_response = cisco_sighting(value, client)

print(inspect_response)
```

However I obtain the following error:
```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://private.intel.eu.amp.cisco.com/ctia/sighting
{
    "errors": {
        "observed_time": "missing-required-key", 
        "query": "disallowed-key"
    }
}
```

Thanks

**Comment by bgreenba** [comment]
Hi - I'm not sure that I can help diretly, but let's start with this: What is the intent of your code here? Check for sightings, or report one?

**Comment by Link009** [comment]
Hi

I would like to check an IOC, to know if there is any Sighting inside Cisco Intel. I saw there is available a way to instantiate Sighting module:

`sighting = client.private_intel.sighting`

But how to use it further ? How do I check the IOC I used above on Sighting module ?

**Comment by bgreenba** [comment]
Remember, observables consist of both a value and a type:
    [{'type': 'url', 'value': 'https://pressabpacam1988.blogspot.ru/'}]

The functions available in the module correspond to the API endpoints. The API endpoint for pivate_intel.sightings is to be used for creating, editing, downloading, or searching sightings. But the POST operation is only for crating new ones, which is why I asked what you were trying to do. 
Use GET, and make sure your observable is properly formatted as above. 

[...]
def search_cisco_sighting(value, client):
    sighting = client.private_intel.sighting
    time.sleep(1)
    return sighting.sightings(observable)
 [...]

sightings=search_cisco_sighting([{'type': 'url', 'value': 'https://pressabpacam1988.blogspot.ru/'}]), client
print(sightings)

Try something more like that.

**Comment by Link009** [comment]
So with this code:

```
def cisco_sighting(value, client):
    sighting = client.private_intel.sighting
    time.sleep(1)
    return sighting.sightings(value)


value = "https://pressabpacam1988.blogspot.ru/"

client = cisco_client()
sightings = cisco_sighting([{'type': 'url', 'value': value}], client)
print(sightings)
```

I got this error:

Traceback (most recent call last):
[
  File "C:/Users/link/Desktop/ss.py", line 28, in <module>

    sightings = cisco_sighting([{'type': 'url', 'value': value}], client)

  File "C:/Users/link/Desktop/ss.py", line 22, in cisco_sighting

    return sighting.sightings(value)

  File "C:\Program Files (x86)\Python27-32\lib\site-packages\threatresponse\api\routing\resolution.py", line 17, in __call__

    return method(self._owner, *args, **kwargs)

TypeError: _perform() takes exactly 3 arguments (2 given)](url)

**Comment by bgreenba** [comment]
You're getting an error because you're still doing it wrong. 

Observables consist of two parts, as I explained above, and showed you in the example. 

Look at the code I gave you, and then at the core you ran. See the difference between my '[{'type': 'url', 'value': 'https://pressabpacam1988.blogspot.ru/'}]' and your 'https://pressabpacam1988.blogspot.ru/'.
For more information, look at this description of the structure of an observable object in CTIM (the Threat Response data model): 
https://github.com/threatgrid/ctim/blob/master/doc/structures/sighting.md#map6

If you want to just pass arbitrary strings to Threat Response and have it decide what type of observable it is, and format it properly for you, then you need to call Inspect first. Otherwise you need ot format it as an Observable.

**Comment by Link009** [comment]
Thanks for the help, but I don't get it. When I call my function, what I pass is the whole list of dictionary which includes type and value. So, inside the function, "value" is equal to `[{'type': 'url', 'value': 'https://pressabpacam1988.blogspot.ru/'}]`.

I changed some terms here to make it clearer but the result is the same as above:

```
def cisco_sighting(observable, client):
    sighting = client.private_intel.sighting
    time.sleep(1)
    return sighting.sightings(observable)


observable = [{'type': 'url', 'value': 'https://pressabpacam1988.blogspot.ru/'}]

client = cisco_client()
sightings = cisco_sighting(observable, client)
print(sightings)
```

Please note that the piece of code here is a copy-paste of the one you posted above, with a correction on putting "client" inside sightings parenthesis.

Also, does this work for you ?

Thanks

**Comment by bgreenba** [comment]
Ah you're right I saw the same value= assignment but did not notice the change in the cisco_sightings() call.

No, I had not run the code. This is apparent by the parenthesis error and the fat that I didn't rename the variables throughout. It was typed out for you hastily to show you the format of the observable structure and how to use the sightings call; this why I said "Try something more like that" and not "Here I wrote it for you"

But I have another question: Are you specifically looking for sightings from Private Intel? Or are you looking for sightings from all of your configured modules? Because unless you are specifically looking for sightings that have been written to your Private Intel data store (probably in the context of snapshots and incidents) then you are using the wrong part of the module entirely. To see Sightings from you modules in your environment, use the enrich API.

I recommend that you read the API documentation in the portal. The functions in the module mirror the API functionality almost exactly, and an understanding of the API will be of great assistance to you working with the module that uses it.

**Comment by bgreenba** [comment]
Also, "Here I wrote it for you"


`
from threatresponse import ThreatResponse

def cisco_client():
    client = ThreatResponse(
        client_id=<YOUR_ID>,
        client_password=<YOUR_PASS>,
        region='eu',
        timeout=900)

    time.sleep(1)
    return client


def enrich_sightings(observable):
	sightings_list = client.enrich.observe.observables(observables)
	time.sleep(1)
	return sightings_list

type = 'url'
value = 'https://pressabpacam1988.blogspot.ru/'
observables = [{'type': type, 'value': value}]

client = cisco_client()
enrich_response = enrich_sightings(observables)

print(enrich_response)
`

This worked for me on the first try, using an observable that had been seen in my environment of course. Hope it helps.

**Comment by Link009** [comment]
Ok. I was using enrich API with observe.observables for 2 weeks by now to get sightings section of an observable. LOL. 
What I was curious about was the Sightings module itself, which seems to stay unknown to me for now.
I mean, ok I can have sightings from observe.observables. So what is the purpose of Sightings module then ?

To answer your question, yes, I need for sightings from private Intel. Or better, I need to use private_intel to get the sightings I need. 

But wait, now, what do you mean with "looking for sightings from all of your configured modules" ? I don't know if term "sighting" is good to indicate results from modules as long as there is a specific sightings section. It may be misleading.

Anyway thanks for your answers. They were useful to clarify some doubts. Do you have any suggestion on the error Sightings module itself produce ?

`TypeError: _perform() takes exactly 3 arguments (2 given)`

Thanks again

**Comment by bgreenba** [comment]
It's not a "sightings module".
It's a function to pull sightings from private intelligence. What is your end goal here? What do you mean by "you need to use private intel to get to the sightings".

I again recommend that you read the documentation.

**Comment by Link009** [comment]
I will read the documentation. Thanks for the help.

**Comment by gdavoian** [comment]
Hope the problem has been solved. Closing the issue.

**Comment by Link009** [comment]
Hi

I am using Observe SMA Endpoint more or less successfully by now.
This is the function I am working on:

```
def cisco_sightings(value, client, inspect_response):
    artifact_type = inspect_response[0]["type"]

    response = client.enrich.observe.observables([{'type': artifact_type, 'value': value}])

    time.sleep(1)
    master_response["cisco_sightings"] = response
    return json.dumps(response, indent=4)
```

However I noted that the max result I have inside response variable is 100 elements. 
[SMA Max count Screenshot](https://i.imgur.com/WdBsol2.png)

How can I retrieve all of them, which for my input value, is way more than 100 ? How many results does observe.observables can return ? Is there any parameter to expand to more than a 100 ?



Thanks

**Comment by bgreenba** [comment]
Hello,

That is correct, the API only passes on the first 100 sightings. This is done to prevent any one misbehaving module from flooding the investigation. If you're looking for sightings of something that has been seen "way more" than 100 times, there's probably a reason to pause and ask why, or if this is the best way to do it.

**Comment by Link009** [comment]
I am trying to implement an automation that count how many email_subject or email_senders has been seen from a given input value (in my case hotmail.it domain).
For sure exist more than 100 results and it would be useful to not lose any subject/sender from all of them (which, now, are truncated by this limit).

I understand the concept of flooding the investigation and is right. But in this case, how should I behave ? Why 100 and not, for example, 1000 ?
